name: 'common'
description: 'A common action'
inputs:
  say:
    description: "what to say"
    required: true
runs:
  using: "composite"
  steps:
    - run: ./.github/actions/common/common.sh "${{ inputs.say }}"
      shell: bash
