name: promote envs
on:
  push:
    branches:
      - dev
jobs:
  say_hello:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - env: 
          SAY: ${{ secrets.SAY }}
        run: ./hello.sh "$SAY" 
