name: promote envs for stage
on:
  push:
    branches:
      - stage
jobs:
  say_hello:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - env: 
          SAY: ${{ secrets.SAY }}
        run: ./hello.sh "$SAY" 
      - id: common_hello
        uses: ./.github/actions/common
        with:
          say: ${{ secrets.SAY }}
