name: promote envs for prd
on:
  push:
    branches:
      - prod
jobs:
  say_hello:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - env: 
          SAY: ${{ secrets.SAY }}
        run: ./hello.sh "$SAY" 
      - id: common_hello
        uses: ./.github/actions/common
        with:
          say: ${{ secrets.SAY }}

