name: promote envs for dev
on:
  push:
    branches:
      - dev
jobs:
  say_hello:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - env: 
          SAY: ${{ secrets.SAY }}
        run: ./hello.sh "$SAY" 
      - id: common_hello
        uses: ./.github/actions/common
        with:
          say: ${{ secrets.SAY }}
      - uses: actions/checkout@master
      - name: Merge to stage
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: stage
          github_token: ${{ github.token }}
